### ISSUE TITLE
Document default "reject" plugin settings

### ISSUE THREAD

**Issue by satterly** [alerta/alerta-docs#59]
@strzelecki-maciek
> hi guys, i have a problem with 403 when alertmanager tries to post an alert to Alerta. I have an apikey, created it as admin use, key is read/write, named prometheus. The counter shows it was used "960 times" so far, and each and every one is 403. What am i missing?
ok, my problem was a missing environment label. this could be made slightly more visible in the docs :)

**Comment by satterly** [comment]
I agree that returning a `403 Forbidden` status code from the Reject plugin is confusing. This should be a `400 Bad Request` indicating to the client that authentication was successful but the request was malformed for some reason.

**Comment by sjal** [comment]
I have the exact same problem but I always had environment label, what am I missing?

**Comment by satterly** [comment]
The `environment` label must match an allowed environment. By default this is either Production or Development. You also must define a `service` but it doesn't matter what it is as long as it's not null.

**Comment by sjal** [comment]
Absolute gamechanger for me, thank you! For other people viewing this - remember the labels are case sensitive - eg. you can't write "production", it has to be "Production" (at least in my case)

**Comment by satterly** [comment]
When the Alerta API starts up now it will print the following to logfiles or stdout...
```
2018-11-27 12:04:31,349 - alerta.plugins[34323]: DEBUG - Server plugin 'reject' installed. [in /Users/nsatterl/Projects/alerta/alerta/utils/plugin.py:30]
2018-11-27 12:04:31,353 - flask.app[34323]: INFO -

    Default reject policy will block alerts that do not have the following
    required attributes:
    1) environment - must match an allowed environment. By default it should
       be either "Production" or "Development". Config setting is `ALLOWED_ENVIRONMENTS`.
    2) service - must supply a value for service. Any value is acceptable.

 [in /Users/nsatterl/Projects/alerta/alerta/plugins/__init__.py:18]
2018-11-27 12:04:31,353 - alerta.plugins[34323]: INFO - Server plugin 'reject' enabled. [in /Users/nsatterl/Projects/alerta/alerta/utils/plugin.py:38]
```

**Comment by satterly** [comment]
Also note that there is a [FAQ where this is mentioned](https://docs.alerta.io/en/latest/faq.html?highlight=disabled#why-do-i-need-to-set-an-environment-and-service-when-they-are-not-mandatory) and [multiple places in the online docs](https://docs.alerta.io/en/latest/search.html?q=reject&check_keywords=yes&area=default).
