### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by mmulqueen** [alerta/alerta-docs#67]
Please can you clarify what is required in terms of manual housekeeping now? The docs still mention `housekeepingAlerts.js`, but I'm running with PostgreSQL so that's not an option.

I see there is a /management/housekeeping view, that I could hit with curl, but should I?

We can use alerta CLI to do the heartbeats, so that's not a concern: `alerta heartbeats --alerta`

I'm happy to bring the documentation up-to-date if you can confirm.

Thanks,
Mike

**Comment by satterly** [comment]
yes you should be using the house keeping API endpoint for version 5 onwards. Where in the docs does it suggest otherwise?

**Comment by mmulqueen** [comment]
@satterly 

Thanks for the speedy reply.

I've seen it two places:

- http://docs.alerta.io/en/latest/deployment.html#house-keeping
- http://docs.alerta.io/en/latest/gettingstarted/tutorial-2-housekeeping.html

I don't think I've found any reference to the /management/housekeeping endpoint, I only found that by browsing the alerta source code repository.

Do you have any recommendations about how often to request that endpoint?

Is there anything built into Alerta CLI to do it or shall I just use curl?

Like I say, happy to make the necessary updates to the docs.

**Comment by satterly** [comment]
I hadn't noticed the old references to the Housekeeping.js script. Thanks for pointing them out.

I think I generally run the housekeeping script every minute. No reason not to run it as regularly as possible, I would have thought. 

And no, there is currently no support for calling the hk endpoint via the CLI. I just use curl. Though that is a reasonable suggestion which I'll consider.

Please go ahead and make the updates to the docs when you get a chance. Thanks again.
