### ISSUE TITLE
AUTH_PROVIDER needs ldap as an option

### ISSUE THREAD

**Issue by wo250012** [alerta/alerta-docs#97]
AUTH_PROVIDER does not have 'ldap' as an option. The docs make it look like you use 'basic' for this, resulting in lots of head scratching.

**Comment by satterly** [comment]
It used to be the case that LDAP was used if the python LDAP library was installed. This was changed to force an explicit setting of `AUTH_PROVIDER` to `ldap` but as you say, the documentation wasn't updated. Should be fixed now. Thanks.

https://docs.alerta.io/en/latest/authentication.html#basic-auth-using-ldap
